const KEY="nexora-health-v2";
let db=JSON.parse(localStorage.getItem(KEY)||"null")||{meds:[],appointments:[],symptoms:[],vitals:[]};
let tab="dashboard";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function nav(){return `<header class="top"><div class="nav"><div class="brand">Nexora Health<small>Your personal health organizer</small></div><div class="row"><button class="btn secondary" onclick="exportData()">Export</button><button class="btn secondary" onclick="document.getElementById('import').click()">Import</button><input id="import" type="file" accept=".json" hidden onchange="importData(event)"></div></div></header>`}
function tabs(){return `<div class="tabs">${["dashboard","medications","appointments","symptoms","vitals"].map(x=>`<button class="tab ${tab===x?"active":""}" onclick="tab='${x}';render()">${x[0].toUpperCase()+x.slice(1)}</button>`).join("")}</div>`}
function dashboard(){return `<div class="hero"><div><h1>Health, organized.</h1><p>Track medications, visits, symptoms and vitals in one private browser-based workspace.</p></div><button class="btn" onclick="tab='vitals';render()">Log a vital</button></div><div class="grid"><div class="card"><div class="muted">Medications</div><div class="metric">${db.meds.length}</div></div><div class="card"><div class="muted">Upcoming visits</div><div class="metric">${db.appointments.filter(x=>x.date>=today()).length}</div></div><div class="card"><div class="muted">Symptom entries</div><div class="metric">${db.symptoms.length}</div></div><div class="card"><div class="muted">Vital records</div><div class="metric">${db.vitals.length}</div></div></div><div class="notice"><b>Privacy:</b> records stay in this browser. No Claude/Anthropic API and no external database are used.</div><div class="section card"><h2>Recent activity</h2>${recent()}</div>`}
function recent(){let a=[...db.symptoms.map(x=>({d:x.date,t:"Symptom: "+x.name})),...db.vitals.map(x=>({d:x.date,t:"Vital: "+x.type})),...db.appointments.map(x=>({d:x.date,t:"Appointment: "+x.title}))].sort((a,b)=>b.d.localeCompare(a.d)).slice(0,6);return a.length?a.map(x=>`<div class="item"><span>${esc(x.t)}</span><span class="muted">${esc(x.d)}</span></div>`).join(""):`<div class="empty">No records yet.</div>`}
function medications(){return `<div class="card"><h2>Add medication</h2><form class="form" onsubmit="addMed(event)"><div class="field"><label>Name</label><input name="name" required placeholder="e.g. Vitamin D"></div><div class="field"><label>Dosage</label><input name="dose" placeholder="e.g. 1000 IU"></div><div class="field"><label>Schedule</label><input name="time" placeholder="e.g. Morning"></div><div class="field"><label>Notes</label><input name="notes"></div><div class="field full"><button class="btn">Add medication</button></div></form></div><div class="section card"><h2>Your medications</h2>${db.meds.length?db.meds.map((x,i)=>`<div class="item"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.dose)} · ${esc(x.time)}</div></div><button class="btn danger" onclick="removeItem('meds',${i})">Delete</button></div>`).join(""):`<div class="empty">No medications added.</div>`}</div>`}
function appointments(){return `<div class="card"><h2>Add appointment</h2><form class="form" onsubmit="addAppointment(event)"><div class="field"><label>Appointment</label><input name="title" required placeholder="Doctor / clinic"></div><div class="field"><label>Date</label><input type="date" name="date" required></div><div class="field"><label>Time</label><input type="time" name="time"></div><div class="field"><label>Notes</label><input name="notes"></div><div class="field full"><button class="btn">Add appointment</button></div></form></div><div class="section card"><h2>Appointments</h2>${db.appointments.length?db.appointments.slice().sort((a,b)=>a.date.localeCompare(b.date)).map((x,i)=>`<div class="item"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.date)} ${esc(x.time||"")} · ${esc(x.notes||"")}</div></div><button class="btn danger" onclick="removeItem('appointments',${db.appointments.indexOf(x)})">Delete</button></div>`).join(""):`<div class="empty">No appointments added.</div>`}</div>`}
function symptoms(){return `<div class="card"><h2>Symptom journal</h2><form class="form" onsubmit="addSymptom(event)"><div class="field"><label>Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Symptom</label><input name="name" required placeholder="e.g. Headache"></div><div class="field"><label>Severity</label><select name="severity"><option>Mild</option><option>Moderate</option><option>Severe</option></select></div><div class="field"><label>Duration</label><input name="duration" placeholder="e.g. 2 hours"></div><div class="field full"><label>Notes</label><textarea name="notes" rows="3"></textarea></div><div class="field full"><button class="btn">Save entry</button></div></form></div><div class="section card"><h2>Journal</h2>${db.symptoms.length?db.symptoms.slice().reverse().map(x=>`<div class="item"><div><b>${esc(x.name)}</b> <span class="badge">${esc(x.severity)}</span><div class="muted">${esc(x.date)} · ${esc(x.duration)} · ${esc(x.notes)}</div></div><button class="btn danger" onclick="removeItem('symptoms',${db.symptoms.indexOf(x)})">Delete</button></div>`).join(""):`<div class="empty">No symptom entries.</div>`}</div>`}
function vitals(){return `<div class="card"><h2>Log vital</h2><form class="form" onsubmit="addVital(event)"><div class="field"><label>Date</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Type</label><select name="type"><option>Blood pressure</option><option>Heart rate</option><option>Temperature</option><option>Weight</option><option>Blood glucose</option></select></div><div class="field"><label>Value</label><input name="value" required placeholder="e.g. 120/80"></div><div class="field"><label>Unit</label><input name="unit" placeholder="bpm, °C, kg..."></div><div class="field full"><button class="btn">Save vital</button></div></form></div><div class="section card"><h2>Vitals history</h2>${db.vitals.length?db.vitals.slice().reverse().map(x=>`<div class="item"><div><b>${esc(x.type)}</b> <span class="badge">${esc(x.value)} ${esc(x.unit)}</span><div class="muted">${esc(x.date)}</div></div><button class="btn danger" onclick="removeItem('vitals',${db.vitals.indexOf(x)})">Delete</button></div>`).join(""):`<div class="empty">No vital records.</div>`}</div>`}
function render(){document.getElementById("app").innerHTML=nav()+`<main class="wrap">${tabs()}${tab==="dashboard"?dashboard():tab==="medications"?medications():tab==="appointments"?appointments():tab==="symptoms"?symptoms():vitals()}<div class="footer">Nexora Health · Personal health organizer · Not for diagnosis or emergencies.</div></main>`}
function addMed(e){e.preventDefault();db.meds.push(Object.fromEntries(new FormData(e.target)));save()}
function addAppointment(e){e.preventDefault();db.appointments.push(Object.fromEntries(new FormData(e.target)));save()}
function addSymptom(e){e.preventDefault();db.symptoms.push(Object.fromEntries(new FormData(e.target)));save()}
function addVital(e){e.preventDefault();db.vitals.push(Object.fromEntries(new FormData(e.target)));save()}
function removeItem(k,i){if(confirm("Delete this record?")){db[k].splice(i,1);save()}}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="nexora-health-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.meds&&x.appointments&&x.symptoms&&x.vitals){db=x;save()}else alert("Invalid Nexora backup")}catch{alert("Invalid JSON file")}};r.readAsText(f)}
render();